/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  114: {
    RadiShield: {
      address: "0x6e4410795200366439B9c1f567f1AE43D777Dd22",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_weatherOracle",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "length1",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "length2",
              type: "uint256",
            },
          ],
          name: "ArrayLengthMismatch",
          type: "error",
        },
        {
          inputs: [],
          name: "ContractNotPaused",
          type: "error",
        },
        {
          inputs: [],
          name: "ContractPaused",
          type: "error",
        },
        {
          inputs: [],
          name: "EmptyArray",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "required",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "available",
              type: "uint256",
            },
          ],
          name: "InsufficientAllowance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "required",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "available",
              type: "uint256",
            },
          ],
          name: "InsufficientBalance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "required",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "available",
              type: "uint256",
            },
          ],
          name: "InsufficientContractBalance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "required",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "provided",
              type: "uint256",
            },
          ],
          name: "InsufficientPremium",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "addr",
              type: "address",
            },
          ],
          name: "InvalidAddress",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "InvalidAmount",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "maxIndex",
              type: "uint256",
            },
          ],
          name: "InvalidArrayIndex",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "coverage",
              type: "uint256",
            },
          ],
          name: "InvalidCoverage",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "cropType",
              type: "string",
            },
          ],
          name: "InvalidCropType",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "duration",
              type: "uint256",
            },
          ],
          name: "InvalidDuration",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "jobId",
              type: "bytes32",
            },
          ],
          name: "InvalidJobId",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "int256",
              name: "lat",
              type: "int256",
            },
            {
              internalType: "int256",
              name: "lon",
              type: "int256",
            },
          ],
          name: "InvalidLocation",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "oracle",
              type: "address",
            },
          ],
          name: "InvalidOracleAddress",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "recipient",
              type: "address",
            },
          ],
          name: "InvalidRecipient",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "InvalidTimestamp",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          name: "InvalidTokenAddress",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "rainfall30d",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "rainfall24h",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "temperature",
              type: "uint256",
            },
          ],
          name: "InvalidWeatherData",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "requestId",
              type: "bytes32",
            },
          ],
          name: "OracleRequestFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "requestId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "timeoutDuration",
              type: "uint256",
            },
          ],
          name: "OracleTimeout",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "OwnableInvalidOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "OwnableUnauthorizedAccount",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "PayoutAlreadyProcessed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "recipient",
              type: "address",
            },
          ],
          name: "PayoutFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "PolicyAlreadyClaimed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "PolicyExpired",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "PolicyNotActive",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "reason",
              type: "string",
            },
          ],
          name: "PolicyNotEligibleForPayout",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "PolicyNotFound",
          type: "error",
        },
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          inputs: [],
          name: "TransferFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
          ],
          name: "UnauthorizedOracle",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "WeatherDataNotAvailable",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroValue",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "farmer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "reason",
              type: "string",
            },
          ],
          name: "ClaimPaid",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "Paused",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "triggerType",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "payoutAmount",
              type: "uint256",
            },
          ],
          name: "PayoutTriggered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "farmer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "coverage",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "cropType",
              type: "string",
            },
          ],
          name: "PolicyCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "coverage",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "int256",
              name: "lat",
              type: "int256",
            },
            {
              indexed: false,
              internalType: "int256",
              name: "lon",
              type: "int256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "premium",
              type: "uint256",
            },
          ],
          name: "PremiumCalculated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "Unpaused",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "rainfall30d",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "rainfall24h",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "temperature",
              type: "uint256",
            },
          ],
          name: "WeatherDataReceived",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "requestId",
              type: "bytes32",
            },
          ],
          name: "WeatherDataRequested",
          type: "event",
        },
        {
          stateMutability: "payable",
          type: "fallback",
        },
        {
          inputs: [],
          name: "AFRICA_MAX_LAT",
          outputs: [
            {
              internalType: "int256",
              name: "",
              type: "int256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "AFRICA_MAX_LON",
          outputs: [
            {
              internalType: "int256",
              name: "",
              type: "int256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "AFRICA_MIN_LAT",
          outputs: [
            {
              internalType: "int256",
              name: "",
              type: "int256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "AFRICA_MIN_LON",
          outputs: [
            {
              internalType: "int256",
              name: "",
              type: "int256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "BASE_PREMIUM_RATE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "DROUGHT_THRESHOLD",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "EXTREME_HEATWAVE_THRESHOLD",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "FLOOD_THRESHOLD",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "HEATWAVE_PAYOUT_RATE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "HEATWAVE_THRESHOLD",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MAX_COVERAGE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MAX_DURATION",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MIN_COVERAGE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MIN_DURATION",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "SEVERE_DROUGHT_THRESHOLD",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "SEVERE_FLOOD_THRESHOLD",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "daysToAdd",
              type: "uint256",
            },
          ],
          name: "addDays",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256[]",
              name: "policyIds",
              type: "uint256[]",
            },
            {
              internalType: "uint256[]",
              name: "amounts",
              type: "uint256[]",
            },
            {
              internalType: "string",
              name: "reason",
              type: "string",
            },
          ],
          name: "batchEmergencyPayout",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "coverage",
              type: "uint256",
            },
            {
              internalType: "int256",
              name: "latitude",
              type: "int256",
            },
            {
              internalType: "int256",
              name: "longitude",
              type: "int256",
            },
          ],
          name: "calculatePremium",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "cropType",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "coverage",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "duration",
              type: "uint256",
            },
            {
              internalType: "int256",
              name: "latitude",
              type: "int256",
            },
            {
              internalType: "int256",
              name: "longitude",
              type: "int256",
            },
          ],
          name: "createPolicy",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "startTime",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "endTime",
              type: "uint256",
            },
          ],
          name: "daysBetween",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "reason",
              type: "string",
            },
          ],
          name: "emergencyPayout",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "recipient",
              type: "address",
            },
          ],
          name: "emergencyWithdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "farmerPolicies",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getActivePoliciesCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getClaimedPoliciesCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getContractBalance",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getContractStats",
          outputs: [
            {
              internalType: "uint256",
              name: "totalPolicies",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "activePolicies",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "claimedPolicies",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalCoverage",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalPremiums",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "contractBalance",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "farmer",
              type: "address",
            },
          ],
          name: "getPoliciesByFarmer",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "getPolicy",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "farmer",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "cropType",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "coverage",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "premium",
                  type: "uint256",
                },
                {
                  internalType: "int256",
                  name: "latitude",
                  type: "int256",
                },
                {
                  internalType: "int256",
                  name: "longitude",
                  type: "int256",
                },
                {
                  internalType: "uint256",
                  name: "startDate",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "endDate",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "isActive",
                  type: "bool",
                },
                {
                  internalType: "bool",
                  name: "claimed",
                  type: "bool",
                },
              ],
              internalType: "struct IRadiShield.Policy",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "getPolicyDurationInDays",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "getRemainingDays",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getTotalCoverage",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getTotalPolicies",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getTotalPremiums",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "getWeatherData",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "rainfall30d",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "rainfall24h",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "temperature",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "timestamp",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "isValid",
                  type: "bool",
                },
              ],
              internalType: "struct IWeatherOracle.WeatherData",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "reason",
              type: "string",
            },
          ],
          name: "handleOracleTimeout",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "int256",
              name: "latitude",
              type: "int256",
            },
            {
              internalType: "int256",
              name: "longitude",
              type: "int256",
            },
          ],
          name: "isLocationInAfrica",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "isPolicyActive",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "isPolicyClaimed",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "isPolicyExpired",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "numDays",
              type: "uint256",
            },
          ],
          name: "isWithinDays",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "pause",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "paused",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "policies",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "farmer",
              type: "address",
            },
            {
              internalType: "string",
              name: "cropType",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "coverage",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "premium",
              type: "uint256",
            },
            {
              internalType: "int256",
              name: "latitude",
              type: "int256",
            },
            {
              internalType: "int256",
              name: "longitude",
              type: "int256",
            },
            {
              internalType: "uint256",
              name: "startDate",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "endDate",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isActive",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "claimed",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "processWeatherData",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "requestWeatherData",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "int256",
              name: "latitude",
              type: "int256",
            },
            {
              internalType: "int256",
              name: "longitude",
              type: "int256",
            },
          ],
          name: "scaleCoordinates",
          outputs: [
            {
              internalType: "int256",
              name: "scaledLat",
              type: "int256",
            },
            {
              internalType: "int256",
              name: "scaledLon",
              type: "int256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "unpause",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "int256",
              name: "scaledLatitude",
              type: "int256",
            },
            {
              internalType: "int256",
              name: "scaledLongitude",
              type: "int256",
            },
          ],
          name: "unscaleCoordinates",
          outputs: [
            {
              internalType: "int256",
              name: "lat",
              type: "int256",
            },
            {
              internalType: "int256",
              name: "lon",
              type: "int256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "int256",
              name: "latitude",
              type: "int256",
            },
            {
              internalType: "int256",
              name: "longitude",
              type: "int256",
            },
          ],
          name: "validateCoordinates",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [],
          name: "weatherOracle",
          outputs: [
            {
              internalType: "contract IWeatherOracle",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
    },
    WeatherOracle: {
      address: "0x223cb9DFE5d4427cF50d1f33C3a3BaAc3DbE72be",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "locationHash",
              type: "bytes32",
            },
          ],
          name: "DataNotFound",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "int256",
              name: "lat",
              type: "int256",
            },
            {
              internalType: "int256",
              name: "lon",
              type: "int256",
            },
          ],
          name: "InvalidCoordinates",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "InvalidTimestamp",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "rainfall30d",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "rainfall24h",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "temperature",
              type: "uint256",
            },
          ],
          name: "InvalidWeatherData",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "OwnableInvalidOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "OwnableUnauthorizedAccount",
          type: "error",
        },
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "maxAge",
              type: "uint256",
            },
          ],
          name: "StaleData",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
          ],
          name: "UnauthorizedOracle",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroAddress",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "oracle",
              type: "address",
            },
          ],
          name: "OracleAuthorized",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "oracle",
              type: "address",
            },
          ],
          name: "OracleRevoked",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "int256",
              name: "latitude",
              type: "int256",
            },
            {
              indexed: true,
              internalType: "int256",
              name: "longitude",
              type: "int256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "requester",
              type: "address",
            },
          ],
          name: "WeatherDataRequested",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "int256",
              name: "latitude",
              type: "int256",
            },
            {
              indexed: true,
              internalType: "int256",
              name: "longitude",
              type: "int256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "rainfall30d",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "rainfall24h",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "temperature",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "WeatherDataUpdated",
          type: "event",
        },
        {
          inputs: [],
          name: "DATA_FRESHNESS_THRESHOLD",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MAX_RAINFALL_24H",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MAX_RAINFALL_30D",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MAX_TEMPERATURE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MIN_TEMPERATURE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "oracle",
              type: "address",
            },
          ],
          name: "authorizeOracle",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "authorizedOracles",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "int256[]",
              name: "latitudes",
              type: "int256[]",
            },
            {
              internalType: "int256[]",
              name: "longitudes",
              type: "int256[]",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "rainfall30d",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "rainfall24h",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "temperature",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "timestamp",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "isValid",
                  type: "bool",
                },
              ],
              internalType: "struct IWeatherOracle.WeatherData[]",
              name: "weatherDataArray",
              type: "tuple[]",
            },
          ],
          name: "batchUpdateWeatherData",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "int256",
              name: "latitude",
              type: "int256",
            },
            {
              internalType: "int256",
              name: "longitude",
              type: "int256",
            },
          ],
          name: "getLastUpdateTime",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "int256",
              name: "latitude",
              type: "int256",
            },
            {
              internalType: "int256",
              name: "longitude",
              type: "int256",
            },
          ],
          name: "getLocationHash",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "int256",
              name: "latitude",
              type: "int256",
            },
            {
              internalType: "int256",
              name: "longitude",
              type: "int256",
            },
          ],
          name: "getWeatherData",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "rainfall30d",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "rainfall24h",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "temperature",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "timestamp",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "isValid",
                  type: "bool",
                },
              ],
              internalType: "struct IWeatherOracle.WeatherData",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "oracle",
              type: "address",
            },
          ],
          name: "isAuthorizedOracle",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "int256",
              name: "latitude",
              type: "int256",
            },
            {
              internalType: "int256",
              name: "longitude",
              type: "int256",
            },
            {
              internalType: "uint256",
              name: "maxAge",
              type: "uint256",
            },
          ],
          name: "isDataFresh",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "int256",
              name: "latitude",
              type: "int256",
            },
            {
              internalType: "int256",
              name: "longitude",
              type: "int256",
            },
          ],
          name: "requestWeatherData",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "oracle",
              type: "address",
            },
          ],
          name: "revokeOracle",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "int256",
              name: "latitude",
              type: "int256",
            },
            {
              internalType: "int256",
              name: "longitude",
              type: "int256",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "rainfall30d",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "rainfall24h",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "temperature",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "timestamp",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "isValid",
                  type: "bool",
                },
              ],
              internalType: "struct IWeatherOracle.WeatherData",
              name: "data",
              type: "tuple",
            },
          ],
          name: "updateWeatherData",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
